### PR TITLE
Upgrade to 0.3.0

### PR DESCRIPTION
**Pull request by ghost**
I think we should bump the version to 0.3.0 and merge the changes from the develop branche into the master.
I'll give a quick summary what have happend so far:

013ded8b3424f42684f0957d6765cdf8aa86f321
It is now possible to configure how a dynamic library should be loaded depending on the platform.
You can also give custom load code to the generator,
useful if loading a library needs extra steps (e.g. checking the platroms abi).

2fb2e2f39984b8b88f069c7cdfb68ce1c74916af
The library now uses relative imports to make it more obvious from where which class is.

The following classes are removed from the public API:
DartSourceWriter
~~Element~~ (Edit: see #8, Element is public again)
Parameter

The name property of Struct, Global and Func was moved to their common base class Element.

9de9d488a2a4d8cc9da931230ef8abd88fa137d0
Adds support for documentation.
To unify the approach for Func, Struct and Global, a property of Struct has been renamed.
This could be considered a breaking change.

Fixes missing requried annotations for the name property of Func, Struct and Global.

33ed62a64faca703cec67af5898ebf224ad1bc27
Fixes a small mistake in the README.md (see #12)

1e654ec4e0e2b141c589584de7f58877fd6244fc
Renamed the class Field to StructField, since its only used for structs.
Since this rename affects a class of the public API, this should be considered a breaking change.

Edit2:
55f95e94add1b5d75f11806b4bcca77f94779c83 
Moved the ffi package from dev_dependencies to dependencies (see #15)

Edit3:
a5cc1048aa358ef346c895c9197f9e11a6e025c1 
Added Library.withoutLoading constructor. The generated code will not care about loading a library; instead, a init(DynamicLibrary) method will be generated, which must be call by the user at runtime to set the DynamicLibrary object. This might be useful, if multiple generated libraries share the same DynamicLibrary instance.

Edit4:
7708c5b4aa14e301c264f0c2b6e43e5f22d2e2ca 
You can now add a preamble, which is copied to the start of a file. Useful for LICENSE information.

Edit5:
03fc292e2de4e058b272f48787d74553875ec964 
The dartfmt process now runs in the shell on Windows (see #16)

Keep in mind that some commits contain (minor) breaking changes.
In my opinion this is ok, since we change the version from 0.2.x to 0.3.0.
Take your time to review and comment all the changes.
If all changes are fine, feel free to accept the PR, ~~update the README, Changelog and pubspec,~~ and publish to pub.

Please leave a comment when you start reviewing so I can estimate when the changes go live 😃 

Edit: @sachaarbonel It would be nice if we could #14 before merging this PR.

Edit6: I've updated the README, CHANGELOG and pubspec, so we are ready to push to pub.

### CODE REVIEW

**Comment by EP-u-NW** [comment]
It has been a month since this PR was opend. I'll wait another week for discussion, then I'll merge it, but I've insufficient access rights to push it to pub.

**Comment by mannprerak2** [comment]
Approx. time as of when this PR will be merged? (and v0.3 will be available?)

**Comment by EP-u-NW** [comment]
@mannprerak2 I'll merge on Wednesday, but am not able to publish it to pub (due to insufficient access rights). If you need v0.3.0 as a dependency in one of your projects, take a look at [this example](https://github.com/EPNW/opus_dart/blob/master/pubspec.yaml).

**Comment by EP-u-NW** [comment]
It has been a month and a week since this PR was opend, without any concerns expressed. I'm merging now.

**Pull request merged**
